version: '3.6'

services:

  mailoney:
    container_name: mailoney
    restart: always
    stop_signal: SIGKILL
    read_only: true
    ports: "25:25"
    volumes: "~/data/mailoney/log:/home/mailoney/logs"
    image: "armedpot/mailoney:${MAILONEY_VERSION}"
